#!/bin/bash


export CONF_PROPS_PATH=./fragnostic-conf-props/src/test/resources/com/fragnostic/conf/props/fragnostic-conf-props.properties


./sbt -v -213 -Dsbt.io.implicit.relative.glob.conversion=allow
